### ISSUE TITLE
Creation of output file fails

### ISSUE THREAD

**Issue by jnelson54** [bocinsky/FedData#31] opened 2017-02-23 15:07 UTC
This looks like a great package but I cannot get any of the data extraction functions to print an output file

I am using the tutorial here
http://zevross.com/blog/2016/03/15/using-the-new-r-package-feddata-to-access-federal-open-datasets-including-interactive-graphics/

as a base but when I get to extracting the precipitation data 

ghcn_NOLA<-get_ghcn_daily(template=extentB, label="ghcn_NOLA",
                          elements="prcp", force.redo = F)

I get the error 
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-inventory.txt
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt
Error in rgdal::writeOGR(stations.sp, dsn = extraction.dir, layer = paste0(label,  : 
  Creation of output file failed

any suggestions?

##Begin Script 
library(FedData)    # for downloading federal data
library(rgdal)      # for reading shapefiles
library(ggmap)      # for mapping and more
library(raster)     # for defining extents and raster processing
library(dplyr)      # for data manipulation
library(leaflet)    # for mapping
library(rgeos)      # for using well known text (readWKT)
library(tidyr)      # for reformatting data.frames
library(xts)        # for working with time series
library(dygraphs)   # for the interactive time series plot
library(sp)         # for working with spatial objects
library(tigris)     # for downloading geography

#pick your area of interst
NOLA<-get_map("New Orleans, LA", zoom=12)
ggmap(NOLA)

#Pull out the box area 
bbox<- attr(NOLA, "bb")
bbox

#Now we have our coordinates
#Lets pull the data
extentB<-polygon_from_extent(raster::extent(bbox$ll.lon, bbox$ur.lon,
                                            bbox$ll.lat, bbox$ur.lat), 
                             proj4string="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
class(extentB)
#lets see if it worked
ggmap(NOLA) + geom_polygon(aes(x=long, y=lat), size=3, color='red',
                             data=extentB, fill=NA)
#Sometimes you need specific shapes for an area 
#the tigris package will locate shape files for you
library(tigris)
extentC<-counties(state="LA") # county extent, not a bounding box
extentC<-extentC[extentC$NAME == "Orleans",]
sp::plot(extentC, col="purple", border=TRUE)

#Ok we have defined an area a couple different ways
#now lets lets get data
#NED data https://lta.cr.usgs.gov/NED
ned_NOLA<-get_ned(template=extentB, label="ned_NOLA", 
                    res="1", force.redo = T)

#Now lets get percipitaton data 
#download from daily climate data GHCN 
#https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/global-historical-climatology-network-ghcn
NHD_NOLA<-get_nhd(template=extentB, label="NHD_NOLA")

**Comment by bocinsky** [comment] 2017-02-24 16:59
Good morning James~

Thanks for letting me know about that truly wonderful blog post! I wasn’t even aware of some of the tools that are available for interactive graphics, so it is really helpful.

I just ran your code and didn’t receive the same error. Sometimes if a download doesn’t complete correctly (which can happen for various reasons), it can bung up future runs of the FedData functions. Can you try running the get_ghcn_daily() function with “force.redo = TRUE”? Please let me know if that works for you. Once loading the GHCN data works once, you can switch force.redo back to FALSE for quick (cached) loading.

Best,
Kyle

**Comment by jnelson54** [comment] 2017-02-27 19:40
Kyle, 

Thanks for getting back to me. I tried that and had some of my students try it as well and we all get the same error. Is there a reason it would work for the elevation and not for the ghcn?

**Comment by bocinsky** [comment] 2017-02-27 22:25
Hi James,
The GHCN data is hosted by NOAA, and is therefore coming from a different server than the elevation data (hosted by the NRCS). But I don’t think that has anything to do with the problem. I just tested on a windows machine, and I too am having trouble writing shape files using the writeOGR() function. By my testing, the problem is occurring because of the trailing slash in the default “extraction.dir” parameter. (Oddly, this should be happening for the NHD as well.) Would you do me a favor and try manually defining the extraction directory without the trailing slash. Something like this:

ghcn_NOLA <- get_ghcn_daily(template=extentB, label="ghcn_NOLA", extraction.dir = "./EXTRACTIONS/ghcn_NOLA/GHCN", elements="prcp", force.redo = F)

It worked on my Windows install, and if it works on yours then it means that the trailing slash is breaking writeOGR(). I’ll be able to work on a patch this afternoon or early tomorrow.

Please let me know.

Thanks,
Kyle

**Comment by jnelson54** [comment] 2017-02-28 00:50
That worked perfectly. Funny it worked for the get_ned command. Thanks for figure it out and thanks for developing such a useful package.

**Comment by bocinsky** [comment] 2017-02-28 00:51
My pleasure. I’m working on a patch and will get it put up tomorrow!

**Comment by bocinsky** [comment] 2017-02-28 23:41
Version 2.4.5 fixes this bug. Submitted to CRAN, and closing this issue.

**Closed by bocinsky** 2017-02-28 23:41 UTC
